apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: tenant-config
    namespace: payment-api
    files:
      - payment-api-config.yaml
