{{- $namespace := .Values.tenantName -}}
{{- $tenantName := include "flux-tenant.name" . -}}
{{- range .Values.additionalServiceAccounts }}
{{- $serviceAccountName := .name }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $serviceAccountName }}
  namespace: {{ $namespace }}
  labels:
    toolkit.fluxcd.io/tenant: {{ $tenantName }}
  annotations:
    helm.sh/resource-policy: keep
{{- range .clusterRoleBindings }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    toolkit.fluxcd.io/tenant: {{ $tenantName }}
  annotations:
    helm.sh/resource-policy: keep
# We need to prefix the name with namespace because ClusterRoleBinding resources are not namespaced
  name: tenant-{{ $namespace }}-{{ $serviceAccountName }}-{{ . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ . }}
subjects:
  - kind: ServiceAccount
    name: {{ $serviceAccountName }}
    namespace: {{ $namespace }}
{{- end }}
{{- end }}
