apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "flux-tenant.name" . }}
  labels:
    toolkit.fluxcd.io/tenant: {{ .Values.tenantName }}
  annotations:
    helm.sh/resource-policy: keep
  namespace: {{ .Values.tenantName }}
